// Statik import'lar — sadece burada listelenen markalar bundle'a girer.
// simple-icons paketi `sideEffects: false` olduğu için tree-shaking düzgün çalışır.
//
// Yeni marka eklemek için: aşağıdaki import'a `siBrandName` ekle ve `BRAND_REGISTRY` map'ine
// `slug: siBrandName` çiftini ekle. Slug'lar simple-icons'ın dosya isimleriyle aynı
// (https://simpleicons.org adresinden bakılabilir).

import {
  si1password,
  siAnthropic,
  siApplemusic,
  siApplepodcasts,
  siAppletv,
  siAsana,
  siBitwarden,
  siClaude,
  siClickup,
  siCloudflare,
  siCoursera,
  siCrunchyroll,
  siCursor,
  siDeezer,
  siDiscord,
  siDropbox,
  siDuolingo,
  siEpicgames,
  siExpressvpn,
  siFigma,
  siFramer,
  siGithub,
  siGitlab,
  siGoogledrive,
  siGooglephotos,
  siGrammarly,
  siHbo,
  siHbomax,
  siIcloud,
  siKick,
  siLastpass,
  siLinear,
  siMailchimp,
  siMax,
  siMedium,
  siMubi,
  siNetflix,
  siNordvpn,
  siNotion,
  siOnlyfans,
  siParamountplus,
  siPatreon,
  siPerplexity,
  siPlaystation,
  siPlex,
  siProton,
  siProtonmail,
  siProtonvpn,
  siRaycast,
  siReplit,
  siSignal,
  siSkillshare,
  siSpotify,
  siStarz,
  siSteam,
  siSubstack,
  siSurfshark,
  siTelegram,
  siThreema,
  siTidal,
  siTodoist,
  siTrello,
  siTwitch,
  siUdemy,
  siVercel,
  siWhatsapp,
  siYoutube,
  siYoutubemusic,
} from 'simple-icons';

import type { SimpleIcon } from 'simple-icons';

// Slug → SimpleIcon. simple-icons içindeki kanonik slug'ları kullanırız.
export const BRAND_REGISTRY: Record<string, SimpleIcon> = {
  '1password': si1password,
  anthropic: siAnthropic,
  applemusic: siApplemusic,
  applepodcasts: siApplepodcasts,
  appletv: siAppletv,
  asana: siAsana,
  bitwarden: siBitwarden,
  claude: siClaude,
  clickup: siClickup,
  cloudflare: siCloudflare,
  coursera: siCoursera,
  crunchyroll: siCrunchyroll,
  cursor: siCursor,
  deezer: siDeezer,
  discord: siDiscord,
  dropbox: siDropbox,
  duolingo: siDuolingo,
  epicgames: siEpicgames,
  expressvpn: siExpressvpn,
  figma: siFigma,
  framer: siFramer,
  github: siGithub,
  gitlab: siGitlab,
  googledrive: siGoogledrive,
  googlephotos: siGooglephotos,
  grammarly: siGrammarly,
  hbo: siHbo,
  hbomax: siHbomax,
  icloud: siIcloud,
  kick: siKick,
  lastpass: siLastpass,
  linear: siLinear,
  mailchimp: siMailchimp,
  max: siMax,
  medium: siMedium,
  mubi: siMubi,
  netflix: siNetflix,
  nordvpn: siNordvpn,
  notion: siNotion,
  onlyfans: siOnlyfans,
  paramountplus: siParamountplus,
  patreon: siPatreon,
  perplexity: siPerplexity,
  playstation: siPlaystation,
  plex: siPlex,
  proton: siProton,
  protonmail: siProtonmail,
  protonvpn: siProtonvpn,
  raycast: siRaycast,
  replit: siReplit,
  signal: siSignal,
  skillshare: siSkillshare,
  spotify: siSpotify,
  starz: siStarz,
  steam: siSteam,
  substack: siSubstack,
  surfshark: siSurfshark,
  telegram: siTelegram,
  threema: siThreema,
  tidal: siTidal,
  todoist: siTodoist,
  trello: siTrello,
  twitch: siTwitch,
  udemy: siUdemy,
  vercel: siVercel,
  whatsapp: siWhatsapp,
  youtube: siYoutube,
  youtubemusic: siYoutubemusic,
};
